### PR TITLE
Adding popTypes to Task.js and Tasks.js

### PR DESCRIPTION
**Pull request by HelderSi**

### CODE REVIEW

**Comment by HelderSi** [comment]
In the first PR I forgot to insert the import lines.

**Comment by filipenevola** [comment]
@HelderSi you can always add new commits to a PR :)

**Comment by HelderSi** [comment]
I didn't know that. Sorry! It was my first PR.
I thought that I'd need the other PR to correct.

**Comment by filipenevola** [comment]
On react 16 propTypes no longer lives inside react npm module, because of that I'll close this PR, I'll open a few issues with improvements that I want to have here and you can help if you want.

**Pull request closed without merging**
